### ISSUE TITLE
CONNECTION_LIST_CONNECTION_WITH_AZ_NULL Error

### ISSUE THREAD

**Issue by msenol86** [awslabs/aws-glue-samples#18]
Hi,

I encounter this error when I try to test my connection which created via Amazon Glue Web interface. I could not find anything on Google or Amazon Forums.

I try to connect my postgresql db which hosted on AWS RDS.

![screenshot from 2018-02-24 04-24-46](https://user-images.githubusercontent.com/2547551/36623936-ba40b500-191a-11e8-8e74-90f3fdee59e8.png)

**Comment by chappidm** [comment]
Did you modify the connection by any chance? You should see an AZ auto-populated in the connection (not visible on console). For example, using CLI, AvailabilityZone=us-west-2a

> aws glue get-connections --region us-west-2
>         {
            "Name": "alpha",
            "ConnectionType": "JDBC",
            "ConnectionProperties": {
                "JDBC_CONNECTION_URL": "jdbc:mysql://alpha.alpha.us-west-2.rds.amazonaws.com:3306/gluedb",
                "PASSWORD": "alpha",
                "USERNAME": "alpha"
            },
            "PhysicalConnectionRequirements": {
                "SubnetId": "subnet-alpha",
                "SecurityGroupIdList": [
                    "sg-alpha"
                ],
                "AvailabilityZone": "us-west-2a"
            },
            "CreationTime": 1519437098.664,
            "LastUpdatedTime": 1519437098.664,
            "LastUpdatedBy": "user/alpha"
        }

**Comment by msenol86** [comment]
I found the issue. I needed to create a S3 Endpoint in VPC Dashboard. Thanks a lot.

**Comment by jcardus** [comment]
I have the same problem. I created the endpoint but didn't work...

**Comment by pguillebert** [comment]
FYI I experienced this issue when fiddling with configs in an existing connection. to fix, i've reselected the same vpc/network (in this order) in the drop-downs, and the problem fixed itself. I think this is an issue with the AWS UI.
