### ISSUE TITLE
Issue With Direct Migration from Hive Metastore to Glue Data Catalog

### ISSUE THREAD

**Issue by kjudahlookout** [awslabs/aws-glue-samples#9]
Hello,
   I hope you are doing well. At my company, we are in the process of adopting Athena for our adhoc data analytics tasks and configured Athena to use Glue data catalogue as its metastore. However, the source of truth for our data is a Hive metastore hosted on an AWS RDS mysql instance and we want Glue data catalog to be in sync with our Hive metastore. For this, we followed instructions outlined on awslabs' aws-glue-samples repo (https://github.com/awslabs/aws-glue-samples/tree/master/utilities/Hive_metastore_migration) to setup a Glue job that we will run (eventually periodically) to directly migrate Hive metastore to Glue data catalog. 

However, we are running into a situation where the job finishes successfully but we don't see anything migrated into our Glue data catalog. I am wondering if this issue is experienced by others and if it got resolved. I do see an issue similar to our issue here (I even replied to this thread): https://github.com/awslabs/aws-glue-samples/issues/6, but this is closed and I dont see a solution posted in it. 

Any help is greatly appreciated. 

Thanks,
Kshitij

**Comment by kjudahlookout** [comment]
Please let me know what more info I can provide to debug this issue. Thanks

**Comment by dichenli** [comment]
Hi Kshitij,

Thank you for using the Glue service. Here are some of my suggestions:

1. Try to run Hive Metastore -> S3 migration as well, see if any data is generated in the S3 bucket. This helps to narrow down the search space for the error.
2. The script hive_metastore_migration.py can migrate your Hive metastore to S3 or a local file system. It is completely open source Spark 2.1 code, you can run the script on your own Spark cluster or a local Spark installation on your laptop, as long as it's connectable to your Hive metastore. Debug locally using this script might be helpful.
3. If you are familiar with Spark programming or Python, you may manually add "print()" debugging statement in the script, then run the script on Glue. It will print to the job output logs in CloudWatch. 
4. Double check if the data is showing up on Glue console. If it shows up on Glue console but not Athena console,  you may need to migrate your Athena catalog to Glue: http://docs.aws.amazon.com/athena/latest/ug/glue-upgrade.html
5. In your use case, if you are looking for a solution to sync from Hive metastore to Glue DataCatalog in near-realtime, you may consider calling Glue DataCatalog APIs directly on a stream processing workflow. You may find Glue DataCatalog APIs documentation here: http://docs.aws.amazon.com/glue/latest/dg/aws-glue-api.html.

**Comment by kjudahlookout** [comment]
Hello,
   Thank you very much for your reply and sorry about the late reply. I was able add some print statements to these Python scripts, run them in Glue and able to see dataframes that is being processed by these scripts. As far as I can see, i didnt see any issue with the dataframes  themselves, i was able to print their count and first 10 rows of dataframes for databases and tables and I can see all the data even after the step in which Spark dataframes get converted to Glue's dynamic frames. 

However, the last step of loading the dynamic frames into glue catalog seems to be (silently) failing for me. Despite printing all data successfully in logs, the data is not getting loaded into glue by glue APIs. 

I am wondering if this is something to do with my old version of hive metastore. My hive metastore version is 1.1.0 which is almost 3 years old. Is it possible that these scripts may have been developed and tested with newer versions of Hive metastore, and may not support old versions such as 1.1.0 as in my case? Pls let me know.

Thanks,
Kshitij

**Comment by dichenli** [comment]
Hmmm... this is really weird. Have you tried to migrate Hive metastore data
into S3? Could you send some sample data in S3 to my email address? Make
sure to mask the confidential fields in the data. I can try to reproduce
the issue, and debug from there.

**Comment by dichenli** [comment]
Also, you may send me your AWS account ID and job run ID through email if
you feel comfortable. I can use it to investigate our service log and see
if anything went wrong.

**Comment by kjudahlookout** [comment]
This issue seems to have been resolved for me with using --region option in the migration scripts. Thanks Dichen Li for the help.
